'use client';
import { useRouter } from 'next/navigation';
import { useFieldArray, useForm } from 'react-hook-form';
import { useMutation } from '@tanstack/react-query';
import { Plus, X } from 'lucide-react';
import { solutionsApi } from '@/lib/api/solutions';
import { Button } from '@/components/ui/Button';
import { TextField, TextareaField, SelectField } from '@/components/ui/FormField';
import { RichTextEditor } from '@/components/shared/RichTextEditor';
import { IconPicker } from '@/components/shared/IconPicker';
import { useToast } from '@/components/ui/Toast';
import styles from '../../admin-shared.module.scss';
type Form={name:string;slug:string;category:'sme'|'ubnd'|'ho_kinh_doanh'|'cuc_nganh'|'chuyen_doi_so';summary:string;content:string;features:{icon:string;title:string;description:string}[]};
const category=[{value:'sme',label:'Doanh nghiệp (SME)'},{value:'ubnd',label:'UBND'},{value:'ho_kinh_doanh',label:'Hộ kinh doanh'},{value:'cuc_nganh',label:'Cục / Ngành'},{value:'chuyen_doi_so',label:'Chuyển đổi số'}];
export default function NewSolutionPage(){const router=useRouter();const{showToast}=useToast();const{register,handleSubmit,control,watch,setValue,formState:{errors}}=useForm<Form>({defaultValues:{name:'',slug:'',category:'sme',summary:'',content:'',features:[]}});const features=useFieldArray({control,name:'features'});const save=useMutation({mutationFn:(v:Form)=>solutionsApi.create({...v,status:'active',is_hot:false,thumbnail:null,features:v.features.map((x,sort_order)=>({...x,sort_order}))}),onSuccess:()=>{showToast('Đã tạo giải pháp');router.push('/admin/solutions')},onError:(e:Error)=>showToast(e.message,'error')});return <div className={styles.page}><div className={styles.header}><div><h1 className={styles.title}>Thêm giải pháp số</h1><p className={styles.muted}>Tạo nội dung và các tính năng nổi bật cho giải pháp.</p></div><Button variant="outline" onClick={()=>router.back()}>Quay lại</Button></div><form className={styles.form} onSubmit={handleSubmit(v=>save.mutate(v))}><div className={styles.grid2}><TextField label="Tên giải pháp" required error={errors.name?.message} {...register('name',{required:'Vui lòng nhập tên giải pháp'})}/><TextField label="Slug" required hint="Ví dụ: quan-ly-ban-hang" {...register('slug',{required:true})}/></div><SelectField label="Nhóm khách hàng" options={category} {...register('category')}/><TextareaField label="Tóm tắt" {...register('summary')}/><RichTextEditor label="Nội dung chi tiết" value={watch('content')} onChange={value=>setValue('content',value)}/><section className={styles.detailSection}><div className={styles.detailHeader}><h3>Tính năng nổi bật</h3><Button type="button" variant="outline" onClick={()=>features.append({icon:'',title:'',description:''})}><Plus className={styles.icon}/> Thêm tính năng</Button></div>{features.fields.map((f,i)=><div className={styles.repeatRow} key={f.id}><IconPicker value={watch(`features.${i}.icon`)} onChange={icon=>setValue(`features.${i}.icon`,icon)}/><TextField label="Tiêu đề" required {...register(`features.${i}.title`)}/><TextareaField label="Mô tả" rows={2} {...register(`features.${i}.description`)}/><button type="button" className={styles.removeRow} onClick={()=>features.remove(i)} aria-label="Xóa tính năng"><X/></button></div>)}</section><div className={styles.actions}><Button type="button" variant="outline" onClick={()=>router.back()}>Hủy</Button><Button type="submit" isLoading={save.isPending}>Tạo giải pháp</Button></div></form></div>}
